version: '3'
services:
  nginx:
    build:
      context: ./nginx-ssl
      dockerfile: ./Dockerfile
    command: []
    depends_on:
      - flask
    ports:
      - "446:443"
  flask:
    restart: always
    build:
      context: ./uwsgi-flask
      dockerfile: ./Dockerfile
    command: []
    volumes:
      - ./auth:/var/www/app
  client_redis:
    image: "redis:alpine"
    command: --port 6381